TimeTracking.Web/Controllers/AdminAccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace TimeTracking.Web.Controllers
{
    [Authorize(Policy = "AdministratorOnly")]
    public class AdminAccountController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
    }
}

TimeTracking.Web/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json.Linq;
using System.Net.Http;
using System.Security.Claims;
using System.Threading.Tasks;
using TimeTracking.Web.Helpers;
using TimeTracking.Web.Models;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace TimeTracking.Web.Controllers
{

    [Authorize(Policy = "EmployeeOnly")]
    public class EmployeeController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Test()
        {
            ClaimsPrincipal cp = User;
            HttpClient client = TimeTrackingAPIClient.GetClient(cp, true);

            //var response0 = await client.GetStringAsync(General.Constants.ApiClient.ApiUrlIdentityEndPoint);
            //var response = await client.GetStringAsync(General.Constants.ApiClient.ApiUrl + "api/values");

            HttpResponseMessage response = await client.GetAsync(General.Constants.ApiClient.ApiUrlIdentityEndPoint);

            if (response.IsSuccessStatusCode)
            {
                string ret = await response.Content.ReadAsStringAsync();
                ViewBag.Json = JArray.Parse(ret);
                return View();
            }
            else
            {
                ErrorView mv = new ErrorView();
                mv.Error = response.StatusCode.ToString();
                mv.Msg = $"Response From TimeTracking API => Access Denied for User : {cp.Identity.Name}";

                return View("Error", mv);
            }
        }
    }
}

TimeTracking.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TimeTracking.Web</title>

    <environment names="Development">
        @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />*@
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-Slate.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/styles.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-controller="Home" asp-action="Index" class="navbar-brand">TimeTracking.Web</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li><a asp-controller="Home" asp-action="Secure">Secure</a></li>
                </ul>

                @await Html.PartialAsync("_RegisterPartial")

            </div>
        </div>
    </div>
    <div class="container body-content">
        @await Component.MotleyFlash("Bootstrap")

        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2016 - TimeTracking.Web</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>

TimeTracking.Web/Views/Shared/_RegisterPartial.cshtml
@using System.Security.Claims
@using TimeTracking.Web.Helpers
@using TimeTracking.General

@if (User.Identity.IsAuthenticated)
{
    <form asp-controller="Account" asp-action="LogOff" method="post" id="logoutForm" class="navbar-right">
        <ul class="nav navbar-nav navbar-right">
            <li><a asp-controller="Account" asp-action="UserInfo" title="Manage">Hello @User.Identity.Name</a></li>

            @if (CheckUserRolePolicies.HasRolePolicy(User, Constants.AppUserPolicyRole.Admin))
            {
                <li><a asp-controller="AdminAccount" asp-action="Index">Admin Page</a></li>
            }

            @if (CheckUserRolePolicies.HasRolePolicy(User, Constants.AppUserPolicyRole.Employee))
            {
                <li><a asp-controller="Employee" asp-action="Index">Employee Page</a></li>
            }



            <li><button type="submit" class="btn btn-link navbar-btn navbar-link">Log off</button></li>
        </ul>
    </form>
    
}
else
{
    <ul class="nav navbar-nav navbar-right">
        <li><a asp-controller="Account" asp-action="Register">Register</a></li>
        <li><a asp-controller="Account" asp-action="Login">Log in</a></li>
    </ul>
}

TimeTracking.Web/Views/Shared/_ValidationSummary.cshtml
<div class="alert alert-danger" hide-if="ViewContext.ModelState.IsValid">
    <strong>Error</strong>
    <div asp-validation-summary="All" class="danger"></div>
</div>